[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/_health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
